#!/bin/sh


echo "--send push notif: start--"

export GIT_DIR=${GIT_DIR-`git rev-parse --git-dir`}
SECRETVALUE=$(cat "$GIT_DIR/../papuchy/papucha-frontend/.discord_link")

echo $SECRETVALUE

# wget -O- "$SECRETVALUE" --post-data "content=new frontend goodies pushin out!, fuck yeah"

curl -X POST "$SECRETVALUE" -H 'Content-Type: application/json' -d '{"content":"new frontend goodies pushin out!, fuck yeah"}'


echo "--send push notif: end--"

exit 0